package br.com.jasaas.enumeration;

public enum PisCofinsTaxStatus {
    STANDARD_TAXABLE_OPERATION,
    DIFFERENTIATED_RATE_TAXABLE_OPERATION,
    ZERO_RATE_TAXABLE_OPERATION ,
    TAXABLE_CONTRIBUTION_OPERATION,
    NON_TAXABLE_OPERATION,
    TAX_SUSPENSION_OPERATION;
}
